name: jbg469 Github Actions
on: push
jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Setup actions
            uses: actions/checkout@v2 
          - name: setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8 #install the python needed
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install django requests requests_toolbelt django-encrypted-model-fields
          - name: Run server
            run: |
              cd ~/AppSec2/GiftCardSite
              python3 manage.py makemigrations LegacySite
              python3 manage.py migrate
              sudo python3 manage.py runserver 81 &
              sleep 10
          - name: Run XSS test
            run: |
              sudo chmod u+x jbg469-xss.py
              sudo python3 jbg469-xss.py
          - name: Run CSRF Tests
            run: |
              sudo chmod u+x jbg-469-csrf.py 
              sudo python3 jbg469-csrf.py              
          - name: Run SQLI Tests
            run: |
              sudo chmod u+x jbg-469-sqli.py 
              sudo python3 jbg469-sqli.py         
          - name: Run CMDI Tests
            run: |
              sudo chmod u+x jbg-469-cmdi.py 
              sudo python3 jbg469-cmdi.py
