name: jbg469 Github Actions
on: push
jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repo content
            uses: actions/checkout@v2
          - name: setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8
          - name: Install dependencies
            run: |
               sudo python3 -m pip install --upgrade pip
               sudo apt-get update
               sudo apt-get install -y apturl
               sudo apt-get install python3-brlapi
               sudo apt-get install -y python3-cupshelpers
               sudo apt-get install python3-louis
               sudo apt-get install -y ubuntu-advantage-tools
               sudo apt-get install unattended-upgrades
               sudo apt-get install python3-requests
               sudo pip install -r requirements.txt
          - name: start server
            run: |
              sudo python3 manage.py runserver 80 &
              sleep 10
          - name: XSS Test
            run: |
              sudo chmod u+x sn3106-xss.py
              sudo python3 sn3106-xss.py
          - name: Run CSRF Tests
            run: |
              sudo chmod u+x jbg-469-csrf.py 
              sudo python3 jbg469-csrf.py              
          - name: Run SQLI Tests
            run: |
              sudo chmod u+x jbg-469-sqli.py 
              sudo python3 jbg469-sqli.py         
          - name: Run CMDI Tests
            run: |
              sudo chmod u+x jbg-469-cmdi.py 
              sudo python3 jbg469-cmdi.py
