name: JBG469 GITHUB ACTIONS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Run server
      run: |
        sudo pip install django
        ls
        cd GiftcardSite
        sudo python3 manage.py runserver 80 > server.out &
        sleep 10
    - name: Run CSRF Tests
      run: |
        python3 jbg469-csrf.py              
    - name: Run SQLI Tests
      run: |
        python3 jbg469-sqli.py         
    - name: Run CMDI Tests
      run: |
        python3 jbg469-cmdi.py
    - name: XSS Test
      run: |
        python3 jbg469-xss.py
